version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - lint
      - tests
  release:
    jobs:
      - build-and-publish-linux-image:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
      - update-description:
          requires:
            - build-and-publish-linux-image
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/python
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Lint
          command: ruff check .
  tests:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/python
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Tests
          command: pytest
      - run:
          name: Upload coverage to Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
  build-and-publish-linux-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: scripts/release_image.sh build
      - run:
          name: Smoke test
          command: scripts/release_image.sh smoke-test
      - run:
          name: Publish image
          command: scripts/release_image.sh publish
  update-description:
    machine: true
    steps:
      - checkout
      - run:
          name: Update Docker Hub description
          command: scripts/release_image.sh update-description
