version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - lint
      - tests

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/python
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Lint
          command: ruff check .
  tests:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/python
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: pip install -r requirements-dev.txt
      - run:
          name: Tests
          command: pytest
      - run:
          name: Upload coverage to Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r python/coverage.xml
